# Generated by Django 6.0.5 on 2026-05-05 20:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_file', models.FileField(upload_to='transcriptions/input/')),
                ('lang', models.CharField(default='fr', max_length=16)),
                ('num_speakers', models.IntegerField(blank=True, null=True)),
                ('speaker_names', models.JSONField(blank=True, default=list)),
                ('model_size', models.CharField(default='medium', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segments', models.JSONField(blank=True, default=list)),
                ('speaker_map', models.JSONField(blank=True, default=dict)),
                ('speakers_found', models.IntegerField(default=0)),
                ('audio_duration_s', models.FloatField(default=0.0)),
                ('timings', models.JSONField(blank=True, default=dict)),
                ('export_txt', models.TextField(blank=True)),
                ('export_srt', models.TextField(blank=True)),
            ],
        ),
    ]
