# Generated by Django 6.0.5 on 2026-05-05 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_initial'),
        ('transcriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcription_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transcriptionjob',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcription_jobs', to='projects.project'),
        ),
        migrations.AddField(
            model_name='transcriptionresult',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='transcriptions.transcriptionjob'),
        ),
    ]
